### ISSUE TITLE
NullPointerException for JSON outline

### ISSUE THREAD

**Issue by mniewrzal** [eclipselabs/eclipse-language-service#75]
I have NPE in outline for JSON file:
```
{
	"test" : 1,
	"aaaa" : 1
}
```
Stacktrace:
```
!ENTRY org.eclipse.ui.navigator 4 2 2016-11-07 10:31:44.985
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.ui.navigator".
!STACK 0
java.lang.NullPointerException
	at org.eclipse.languageserver.outline.LSSymbolsContentProvider.getChildren(LSSymbolsContentProvider.java:85)
	at org.eclipse.languageserver.outline.LSSymbolsContentProvider.hasChildren(LSSymbolsContentProvider.java:116)
	at org.eclipse.ui.internal.navigator.extensions.SafeDelegateTreeContentProvider.hasChildren(SafeDelegateTreeContentProvider.java:112)
	at org.eclipse.ui.internal.navigator.NavigatorContentServiceContentProvider.callNormalHasChildren(NavigatorContentServiceContentProvider.java:444)
	at org.eclipse.ui.internal.navigator.NavigatorContentServiceContentProvider.access$4(NavigatorContentServiceContentProvider.java:439)
	at org.eclipse.ui.internal.navigator.NavigatorContentServiceContentProvider$3.run(NavigatorContentServiceContentProvider.java:407)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.navigator.NavigatorContentServiceContentProvider.hasChildren(NavigatorContentServiceContentProvider.java:392)
	at org.eclipse.ui.internal.navigator.NavigatorContentServiceContentProvider.hasChildren(NavigatorContentServiceContentProvider.java:436)
```

**Comment by mickaelistria** [comment]
Should be fixed with https://github.com/eclipselabs/eclipse-language-service/commit/0895d1e5b7a944519bcd243d9c04c0fc1f41ee7d

**Comment by mniewrzal** [comment]
Yes, works ok now.
