### ISSUE TITLE
NullPointerException with hover and JSON file

### ISSUE THREAD

**Issue by mniewrzal** [eclipselabs/eclipse-language-service#99]
Move mouse over false in provided sample:
```json
{
	"aaaa": 		1,
	"bbbb": 		false
}
```
Stacktrace:
```
java.lang.NullPointerException
	at org.eclipse.languageserver.operations.hover.LSBasedHover.getHoverInfo(LSBasedHover.java:44)
	at org.eclipse.ui.internal.genericeditor.CompositeTextHover.getHoverInfo2(CompositeTextHover.java:48)
	at org.eclipse.jface.text.TextViewerHoverManager$4.run(TextViewerHoverManager.java:166)
```

**Comment by mniewrzal** [comment]
This is fixed already.
